import type { KidProfile, KidAppearance, KidToy } from "@/types"

export function formatAge(age: number, age_months: number): string {
  if (age === 0 && age_months === 0) return "a newborn"
  if (age === 0) return `${age_months} month${age_months === 1 ? "" : "s"} old`
  if (age_months === 0) return `${age} year${age === 1 ? "" : "s"} old`
  return `${age} year${age === 1 ? "" : "s"} and ${age_months} month${age_months === 1 ? "" : "s"} old`
}

function buildAppearanceSummary(appearance: KidAppearance): string {
  const parts: string[] = []
  if (appearance.hair)
    parts.push(`${appearance.hair} hair`)
  else if (appearance.hair_color && appearance.hair_style)
    parts.push(`${appearance.hair_color} ${appearance.hair_style} hair`)
  else if (appearance.hair_color)
    parts.push(`${appearance.hair_color} hair`)
  if (appearance.eye_color) parts.push(`${appearance.eye_color} eyes`)
  if (appearance.skin_tone) parts.push(`${appearance.skin_tone} skin`)
  if (appearance.glasses) parts.push("wears glasses")
  if (appearance.freckles) parts.push("has freckles")
  if (appearance.other) parts.push(appearance.other)
  return parts.join(", ")
}

function buildToySummary(toy: KidToy): string {
  if (!toy.name) return ""
  let result = toy.name
  if (toy.description) result += `, ${toy.description}`
  else if (toy.type) result += ` (a ${toy.type})`
  if (toy.backstory) result += `. ${toy.backstory}`
  return result
}

// Joins a list of names naturally: "Emma", "Emma and Jake", "Emma, Jake, and Sophie"
export function joinNames(names: string[]): string {
  if (names.length === 1) return names[0]
  if (names.length === 2) return `${names[0]} and ${names[1]}`
  return names.slice(0, -1).join(", ") + ", and " + names[names.length - 1]
}

// Builds the prompt_summary string stored on the profile row.
export function buildPromptSummary(
  profile: Pick<KidProfile, "name" | "age" | "age_months" | "gender" | "appearance" | "personality_tags" | "toy">
): string {
  const parts: string[] = []

  if (profile.gender)
    parts.push(`${profile.name} is a ${profile.gender}.`)

  const appearance = buildAppearanceSummary(profile.appearance)
  if (appearance) parts.push(`${profile.name} has ${appearance}.`)

  if (profile.personality_tags.length > 0)
    parts.push(`${profile.name} is ${profile.personality_tags.join(", ")}.`)

  const toy = buildToySummary(profile.toy)
  if (toy) parts.push(`Their favorite toy is ${toy}.`)

  return parts.join(" ")
}

// Builds a prompt for generating a neutral character reference portrait.
export function buildReferenceImagePrompt(profile: KidProfile): string {
  const age = formatAge(profile.age, profile.age_months ?? 0)
  const humanGender = profile.gender === "girl" ? "human girl"
    : profile.gender === "boy" ? "human boy"
    : "human child"
  const appearance = buildAppearanceSummary(profile.appearance)
  const toy = buildToySummary(profile.toy)

  let desc = `${profile.name}, a ${age} old ${humanGender}`
  if (appearance) desc += ` with ${appearance}`

  // Toy is described as a held object — explicitly separate from the character's body
  const toyClause = toy
    ? ` ${profile.name} is holding a toy plushie: ${toy}. The toy is a separate stuffed object in ${profile.name}'s hands, not part of ${profile.name}'s body or appearance.`
    : ""

  return `Full body portrait of ${desc}. ${profile.name} is a human child, not an animal.${toyClause} Facing forward, simple white background, children's picture book character reference, clear and detailed facial features, consistent character design.`
}

// Builds a detailed character description for image prompts when no reference image is available.
// outfits maps character name → outfit string generated by extractStoryVisuals.
export function buildCharacterAnchor(
  profiles: KidProfile[],
  outfits: Record<string, string> = {}
): string {
  const describe = (p: KidProfile) => {
    const age = formatAge(p.age, p.age_months ?? 0)
    const humanGender = p.gender === "girl" ? "human girl"
      : p.gender === "boy" ? "human boy"
      : "human child"
    const appearance = buildAppearanceSummary(p.appearance)
    const toy = buildToySummary(p.toy)
    const outfit = outfits[p.name] ?? ""

    let desc = `${p.name} (${humanGender}, ${age}`
    if (appearance) desc += `, ${appearance}`
    if (outfit) desc += `, ${outfit}`
    desc += ")"
    // Toy is clearly separated as a held object, not a character attribute
    if (toy) desc += `. ${p.name}'s toy (a separate stuffed object ${p.name} holds, not part of their body): ${toy}`
    return desc
  }

  if (profiles.length === 1) return describe(profiles[0])
  return profiles.map(describe).join(". ")
}

// Slim version used when a group reference image is available via Kontext.
// Characters whose IDs are in referenceProfileIds get slim treatment — appearance
// is visible in the reference image. Characters without a reference still get full descriptions.
export function buildCharacterAnchorSlim(
  profiles: KidProfile[],
  outfits: Record<string, string> = {},
  referenceProfileIds: Set<string> = new Set()
): string {
  const describe = (p: KidProfile) => {
    const outfit = outfits[p.name] ?? ""
    const hasReference = referenceProfileIds.has(p.id)

    if (hasReference) {
      // Reference image is the visual authority — trust it completely.
      // Repeating appearance text alongside a reference image creates competing signals.
      const humanGender = p.gender === "girl" ? "human girl"
        : p.gender === "boy" ? "human boy"
        : "human child"
      let desc = `${p.name} (${humanGender})`
      if (outfit) desc += ` wearing ${outfit}`
      return desc
    }

    // Secondary character without a reference image — full description
    const age = formatAge(p.age, p.age_months ?? 0)
    const humanGender = p.gender === "girl" ? "human girl"
      : p.gender === "boy" ? "human boy"
      : "human child"
    const appearance = buildAppearanceSummary(p.appearance)
    const toy = buildToySummary(p.toy)
    let desc = `${p.name} (${humanGender}, ${age}`
    if (appearance) desc += `, ${appearance}`
    if (outfit) desc += `, ${outfit}`
    desc += ")"
    if (toy) desc += `. ${p.name}'s toy (a separate stuffed object, not part of their body): ${toy}`
    return desc
  }

  if (profiles.length === 1) return describe(profiles[0])
  return profiles.map(describe).join("; ")
}

// Fills template placeholders for a single profile
export function fillPromptTemplate(template: string, profile: KidProfile): string {
  const appearanceSummary = buildAppearanceSummary(profile.appearance)
  const toySummary = buildToySummary(profile.toy)
  const ageStr = formatAge(profile.age, profile.age_months ?? 0)

  return template
    .replace(/{{child_name}}/g, profile.name)
    .replace(/{{child_age}}/g, ageStr)
    .replace(/{{child_gender}}/g, profile.gender ?? "")
    .replace(/{{prompt_summary}}/g, profile.prompt_summary)
    .replace(/{{appearance_summary}}/g, appearanceSummary)
    .replace(/{{toy_summary}}/g, toySummary)
    .replace(/{{personality_tags}}/g, profile.personality_tags.join(", "))
}

// Fills template placeholders for multiple profiles.
// Falls back to single-profile logic when only one profile is provided.
export function fillPromptTemplateMulti(template: string, profiles: KidProfile[]): string {
  if (profiles.length === 1) return fillPromptTemplate(template, profiles[0])

  const names = joinNames(profiles.map(p => p.name))
  const ages = joinNames(profiles.map(p => formatAge(p.age, p.age_months ?? 0)))

  const combinedSummary = profiles
    .map(p => {
      const age = formatAge(p.age, p.age_months ?? 0)
      return `${p.name} (${age}): ${p.prompt_summary}`
    })
    .join(" ")

  const combinedAppearance = profiles
    .map(p => {
      const a = buildAppearanceSummary(p.appearance)
      return a ? `${p.name} has ${a}` : ""
    })
    .filter(Boolean)
    .join("; ")

  const combinedToys = profiles
    .map(p => {
      const t = buildToySummary(p.toy)
      return t ? `${p.name}'s favorite toy is ${t}` : ""
    })
    .filter(Boolean)
    .join("; ")

  const combinedTags = [...new Set(profiles.flatMap(p => p.personality_tags))].join(", ")

  return template
    .replace(/{{child_name}}/g, names)
    .replace(/{{child_age}}/g, ages)
    .replace(/{{child_gender}}/g, profiles.map(p => p.gender ?? "").filter(Boolean).join(", "))
    .replace(/{{prompt_summary}}/g, combinedSummary)
    .replace(/{{appearance_summary}}/g, combinedAppearance)
    .replace(/{{toy_summary}}/g, combinedToys)
    .replace(/{{personality_tags}}/g, combinedTags)
}
